---
title: "Trabajo grupal 1"
author: "20939361-1"
date: '2022-04-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abrir datos

```{r, echo=TRUE}

# -----------------------------------------------
# abrir datos
# -----------------------------------------------

data_ptsd <- read.csv(
  url(
'https://raw.githubusercontent.com/dacarras/psi2301_examples/master/data/ptsd_data.csv'
  )
)


# -----------------------------------------------
# copia de datos para ejemplos
# -----------------------------------------------

data_original <- read.csv(
  url(
'https://raw.githubusercontent.com/dacarras/psi2301_examples/master/data/ptsd_data.csv'
  )
)


```

# Abrir datos

```{r, echo=TRUE}

# -----------------------------------------------
# cargar librerias
# -----------------------------------------------


library(dplyr)

library(labelled)


```

# Descriptivos con war7

```{r, echo=TRUE, eval = FALSE}

# -----------------------------------------------
# descriptivos
# -----------------------------------------------

#---------------------------------------------------------------
#variable 1: Experiencia personal en la guerra, si ha visto a su familia atacada
#war1: ticket siesque si, nada siesque no

tabla1 <- table(data_ptsd$war7)
dplyr::count (data_ptsd,war7)

tabla1(data_ptsd$war7)


barplot(table(data_ptsd$war7),col="#FFDAB9",main = "Experiencia personal en la guerra",names.arg = c("no", "si"),ylab = "Frecuencia", ylim= c(0,75), las=2,cex.names=.8, xlab = "Ha visto cómo su familia fue atacada")

#medidas de tendencia
mean(data_ptsd$war7)
median(data_ptsd$war7)
sd(data_ptsd$war7)
min(data_ptsd$war7)
max(data_ptsd$war7)
percentiles=data_ptsd$war7
quantile(percentiles, c(.25, .75))        


```

# Descriptivos con fut2

## Recategorizacion 1

```{r, echo=TRUE}

# -----------------------------------------------
# descriptivos
# -----------------------------------------------

#---------------------------------------------------------------     
#variable 2: "Experiencia personal de trauma de guerra"
#fut2 = "What do you think; will there be another civil war in Sierra Leone within the next 10 years"
#grafico de barras recategorizado 4 categorias.

dplyr::count(data_ptsd, fut2)

#--------------

data_ptsd %>%
mutate(fut2_4_cat = case_when(
	fut2 == 1 ~ 1, # certainly -> probablemente
	fut2 == 2 ~ 1, # probably  -> probablemente
	fut2 == 3 ~ 2, # undecided -> no lo se
	fut2 == 4 ~ 3, # probably not  -> probablemente no
	fut2 == 5 ~ 4  # certainly not -> no
	)) %>%
with(., table(fut2_4_cat)) %>%
barplot(.,
	col  = "#CAFF70", 
	main = "Presunción de guerra civil según civiles",
	xlab = "Sensación de probabilidad de otra guerra civil dentro de 10 años",
	names.arg = 
	c("probablemente",
		"no lo se",
		"probablemente no",
		"no"),
	ylab = "Frecuencia",
	ylim= c(0,55)
)

#medidas de tendencia    
mean(data_ptsd$fut2)
median(data_ptsd$fut2)
min(data_ptsd$fut2)
max(data_ptsd$fut2)
sd(data_ptsd$fut2)
percentiles=data_ptsd$fut2
quantile(percentiles, c(.25, .75))  

```

# Descriptivos con noe5

```{r, echo=TRUE}

# -----------------------------------------------
# descriptivos
# -----------------------------------------------

#------------------------------------------------------------------
#variable3: No juzgo a un desconocido por su pasado como "rebelde" o no
#noe5= " If I meet a person, I look at this person and don’t care whether he was a rebel or not"
#grafico de barras
  
tabla3 <- table(data_ptsd$noe5)
data_ptsd$noe5 [data_ptsd$noe5 >= 4 & data_ptsd$noe5 <= 5] = 4
dplyr::count (data_ptsd,noe5)

barplot(table(data_ptsd$noe5), col="mistyrose", main= "Nivel de prejuicio en torno a rebeldes", xlab = "Juzgo a un desconocido por su pasado como rebelde", names.arg = c("para nada","no tanto","aveces", "si"),
     ylab = "Frecuencia", ylim= c(0,70))
     

#medidas de tendencia
mean(data_ptsd$noe5)
median(data_ptsd$noe5)
sd(data_ptsd$noe5)
min(data_ptsd$noe5)
max(data_ptsd$noe5)


```

# Descriptivos con ansiedad intergrupal

```{r, echo=TRUE}

# -----------------------------------------------
# descriptivos
# -----------------------------------------------

#-----------------------------------------------------------------
#variable 4: ¿Como las emociones que sienten las personas al interactuar con los rebeldes afecta para que puedan perdonarlos y avanzar a una reconstruccion social?
#histograma

data_ptsd$emociones_reb = with(data_ptsd, rowMeans(cbind(anx2,anx3,anx5,anx6), na.rm=TRUE))

hist(data_ptsd$emociones_reb, ylim=c(0,20),col="aliceblue",main= "Sensaciones al enfrentarse con un rebelde",
     xlab=" Sensaciones",
     ylab="Frecuencia" ,breaks =6)

dplyr::count (data_ptsd,emociones_reb)

#cruce de variables

data_ptsd %>%
  select(emociones_reb, war7) %>%  
  group_by(factor(war7,    
                  labels =
                    c("no", "si"))) %>%  
  summarise(media = mean(emociones_reb, na.rm = TRUE),  
            mediana = median(emociones_reb, na.rm = TRUE),
            desviacion_estandar= sd(emociones_reb, na.rm = TRUE),
            minimo = min(emociones_reb, na.rm = TRUE),
            maximo = max(emociones_reb, na.rm = TRUE)) %>%
  knitr::kable(digits = 2,   #dar formato a tabla
               booktabs= TRUE,
               col.names =
                 c("Ver ataque a familiar","media","mediana","desviación estándar", "mín.", "máx."),  
               caption = "Descriptivos sensaciones según si ha visto a su familia siendo atacada")
              
#medidas de tendencia
mean(data_ptsd$emociones_reb)
median(data_ptsd$emociones_reb)
sd(data_ptsd$emociones_reb)
min(data_ptsd$emociones_reb)
max(data_ptsd$emociones_reb)

```

# Descriptivos con disposición a perdonar

```{r, echo=TRUE}

# -----------------------------------------------
# descriptivos
# -----------------------------------------------

#------------------------------------------------------------
##variable 5, construida: disposición de las personas para perdonar y reconstruir

data_ptsd$disp = with(data_ptsd, rowMeans(cbind(for1,for5,for6), na.rm=TRUE))


hist(data_ptsd$disp, ylim=c(0,40),col="darkolivegreen2",main= "Disposición para perdonar y reconstruir Sierra Leona",
     xlab=" Grado de rencor hacia rebeldes",
     ylab="Frecuencia" ,breaks =6)

dplyr::count (data_ptsd,disp)

#medidas de tendencia
mean(data_ptsd$disp)
median(data_ptsd$disp)
sd(data_ptsd$disp)
min(data_ptsd$disp)
max(data_ptsd$disp)

```

## Gráfico              

```{r, echo=TRUE, eval = FALSE}

# -----------------------------------------------
# plot
# -----------------------------------------------


#cruce de variables

data_ptsd %>%
  select(disp, fut2) %>%  
  group_by(factor(fut2,    
                  labels =
                    c("probablemente","no lo sé","probablemente no", "no"))) %>%  
  summarise(media = mean(disp, na.rm = TRUE),  
            mediana = median(disp, na.rm = TRUE),
            desviacion_estandar= sd(disp, na.rm = TRUE),
            minimo = min(disp, na.rm = TRUE),
            maximo = max(disp, na.rm = TRUE)) %>%
  knitr::kable(digits = 2,   #dar formato a tabla
               booktabs= TRUE,
               col.names =
                 c("expectativa a guerra","media","mediana","desv. estándar", "mín.", "máx."),  
               caption = "Descriptivos disposición hacia el perdón a los rebeldes según su expectativa de una próxima guerra")
   

```

# Entrega 2

## t test version 1              

```{r, echo=TRUE}

# -----------------------------------------------
# plot
# -----------------------------------------------

# t test variable cuanti vs cuali
# WAR7 -> HA VISTO A SU FMILIA SIENDO ATACADA (si/no)
# fut2 -> CREES QUE HABRÁ UNA GUERRA CIVIL DENTRO DE 10 AÑOS? 

data_ptsd %>%
dplyr::select(for1, for5, for6) %>%
psych::alpha()

#--------------------------------------
# prueba t
#--------------------------------------

#repito fórmula de disp
data_ptsd$disp = with(data_ptsd, rowMeans(cbind(for1,for5,for6), na.rm=TRUE))

#t test

t.test(formula = disp ~ war7,
data = data_ptsd,
alternative = c("two.sided"),
mu = 0,
paired = FALSE,
var.equal = TRUE,
conf.level = 0.95)
 
boxplot(disp ~ war7, data = data_ptsd, main = "Disposición para perdonar y construir según la experiencia vivida en la guerra civil",
xlab = "Experiencia", ylab="disposición perdonar y recontruir", col="aliceblue")


```


## Seccion de ANOVA (version 1)

```{r, echo=TRUE}

#------------------------------------------------------------------------------
# ANOVA
#------------------------------------------------------------------------------
 
#codigo denuevo fut2

data_ptsd$fut2 [data_ptsd$fut2 >= 1 & data_ptsd$fut2 <= 2] = 1
data_ptsd$fut2 [data_ptsd$fut2> 2 & data_ptsd$fut2 <= 3] = 2
data_ptsd$fut2 [data_ptsd$fut2 > 3 & data_ptsd$fut2 <= 4] = 3
data_ptsd$fut2 [data_ptsd$fut2 > 4 & data_ptsd$fut2 <= 5] = 4
	
#emociones denuevo
data_ptsd$emociones_reb = with(data_ptsd, rowMeans(cbind(anx2,anx3,anx5,anx6), na.rm=TRUE))

#------------------------------------------------------------
#prueba anova
#------------------------------------------------------------

#1#
#crear variable

data_ptsd$emociones_reb = with(data_ptsd, rowMeans(cbind(anx2,anx3,anx5,anx6), na.rm=TRUE))


dplyr::count (data_ptsd,emociones_reb)

#anova

"anova1" <- aov(fut2 ~ emociones_reb, data = data_ptsd)

aov(fut2 ~ emociones_reb, data = data_ptsd)%>%
 summary()
 
 
boxplot(emociones_reb ~ fut2,data=data_ptsd, main=" Anova 1",
   xlab="sensación al enfrentarse a un rebelde", ylab="fut2", col = "pink")


```


## Seccion de ANOVA (version 2)

```{r, echo=TRUE}

#------------------------------------------------------------
# Anova con datos originales
#------------------------------------------------------------


#------------------------------------------------------------
# preparar datos
#------------------------------------------------------------


data_model <- data_original %>%
              mutate(fut_recat = case_when(
                fut2 == 1 ~ 'neg',
                fut2 == 2 ~ 'neg',
                fut2 == 3 ~ 'neg',
                fut2 == 4 ~ 'neg',
                fut2 == 5 ~ 'pos'
                )) %>%
              mutate(anxiety = psi2301::mean_score(anx2,anx3,anx5,anx6)) %>%
              mutate(disp = psi2301::mean_score(for1, for5, for6)) %>%
              dplyr::glimpse()

#------------------------------------------------------------
# ajustar ANOVA
#------------------------------------------------------------

aov(anxiety ~ fut_recat, data = data_model) %>%
summary()

#------------------------------------------------------------
# plot
#------------------------------------------------------------

boxplot(anxiety ~ fut_recat,
        data=data_model, 
        # main="Anova 1",
        xlab="sensación al enfrentarse a un rebelde", 
        ylab="anxiedad intergrupal", 
        col = "pink"
        )


#------------------------------------------------------------
# descriptivos
#------------------------------------------------------------

data_model %>%
group_by(fut_recat) %>%
summarize(
  media = mean(anxiety, na.rm = TRUE),
  sd = sd(anxiety, na.rm = TRUE),
  n = n()
  ) %>%
knitr::kable(., digits = 2)


```

## Seccion de ANOVA y post hoc (codigo no funciona)

```{r, echo=TRUE, eval = FALSE}


#------------------------------------------------------------
# ANOVA y TUKEY
#------------------------------------------------------------
# no supe como hacerla, me tira error
tuckeyHSD("anova1")

#2#

"anova2" <- aov(fut2 ~ disp, data = data_ptsd)

aov(fut2 ~ disp, data = data_ptsd)%>%
 summary()
 

boxplot(disp ~ fut2,data=data_ptsd, main=" Anova 2",
   xlab="disposición para perdonar y reconstruir Sierra Leona", ylab="fut2", col = "orange")

# tukey post hoc
#------------------------------------------------

#no supe como hacerla, me tira error
tuckeyHSD("anova2")

```

## ANOVA sin efecto

```{r, echo=TRUE, eval = FALSE}



#------------------------------------------------------------
# anova
#------------------------------------------------------------


aov(disp ~ fut_recat, data = data_model) %>%
summary()

boxplot(disp ~ fut_recat,data=data_model)


```

